import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Stack } from '@mui/material'

export default function Home({ providers }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      <Stack spacing={14} alignItems="center">
        <h1 className={styles.title}>
          Welcome to Spotify Capsule Thing!
        </h1>

        <Button variant="contained"  
                size="large"
                onClick={() => signIn(providers.id, {callbackUrl: "/"})}
                sx={{
                  backgroundColor: "#1DB954",
                  '&:hover': {backgroundColor: '#33c065'},
                  color: "white",
        }}>
          Login to Spotify
        </Button>
        <p className={styles.description}>
        UNDER CONSTRUCTION
        </p>
        
      </Stack>
       
        
      </main>
      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
